apiVersion: v1
kind: Secret
metadata:
  name: pan-mgmt-secret
  namespace: kube-system
type: Opaque
stringData:
 # Panorama Auth Key
  PAN_PANORAMA_AUTH_KEY: "750734108430292"
  # Thermite Certificate retrieval 
  #CN-SERIES-AUTO-REGISTRATION-PIN-ID: "758e18ca-f5d4-49b1-b0dc-719c5744516a"
  #CN-SERIES-AUTO-REGISTRATION-PIN-VALUE: "a8e1f50a1e904640b05100b6c3d5c05a"
#Non-mandatory parameters
  # Uncomment this for CSP overide 
  #CN-SERIES-AUTO-REGISTRATION-API-CSP: "<csp-url>" 
